---
- hosts: ec2_pub
  become: yes
  tasks:
  
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install basic packages
    apt:
      pkg:
        - tree
        - nmap
      state: latest

  - name: Install basic packages for Docker
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - python3-pip
      state: latest

  - pip:
      name: docker

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: install docker-ce
    apt:
      name: docker-ce
      state: latest

  - name: pull nginx image
    docker_image:
      name: nginx
      source: pull